#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DST="$ROOT/.env"

# ── Prerequisite checks ──────────────────────────────────────────────────────
echo "🔍 Checking prerequisites ..."

missing=0

if ! command -v python3 >/dev/null 2>&1; then
  echo "  ✗ python3 is not installed or not on PATH." >&2
  missing=1
else
  echo "  ✓ python3  $(python3 --version 2>&1 | head -1)"
fi

if ! command -v docker >/dev/null 2>&1; then
  echo "  ✗ docker is not installed or not on PATH." >&2
  missing=1
else
  echo "  ✓ docker   $(docker --version 2>&1 | head -1)"
fi

if docker compose version >/dev/null 2>&1 || docker compose --version >/dev/null 2>&1; then
  echo "  ✓ compose  $(docker compose version 2>&1 | head -1 || docker compose --version 2>&1 | head -1)"
elif command -v docker-compose >/dev/null 2>&1; then
  echo "  ✓ compose  $(docker-compose --version 2>&1 | head -1)"
else
  echo "  ✗ docker compose (or docker-compose) is not installed." >&2
  missing=1
fi

# Check .env directory is writable
env_dir="$(dirname "$DST")"
if [ ! -d "$env_dir" ] || [ ! -w "$env_dir" ]; then
  echo "  ✗ Directory $env_dir is not writable." >&2
  missing=1
else
  echo "  ✓ .env dir  $env_dir is writable"
fi

if [ "$missing" -ne 0 ]; then
  echo "" >&2
  echo "Prerequisites not met. Install missing tools and retry." >&2
  exit 1
fi

echo ""

# ── Guard: don't clobber existing .env ──────────────────────────────────────
if [ -f "$DST" ]; then
  echo "$DST already exists; leaving it unchanged."
  exit 0
fi

# ── Generate .env ────────────────────────────────────────────────────────────
echo "📝 Creating .env with generated secrets ..."

python3 - "$DST" <<'PY'
from pathlib import Path
import base64
import secrets
import sys

dst = Path(sys.argv[1])

def token(n=32):
    return secrets.token_urlsafe(n)

def b64_key():
    return "base64:" + base64.b64encode(secrets.token_bytes(32)).decode()

text = f"""# Synapse local lab config.
# Generated by scripts/e2e/setup.sh. Do not commit real .env files.

COMPOSE_PROJECT_NAME=synapse-e2e
GENERIC_TIMEZONE=UTC
PUID=1000
PGID=1000

# Host ports are bound to 127.0.0.1 by docker-compose.e2e.yml.
SYNAPSE_SERVICE_PORT=15515
WIKIJS_PORT=3000
QDRANT_PORT=6333
OLLAMA_PORT=11434

# Container image tags.
SYNAPSE_SERVICE_IMAGE=synapse-service:local
QDRANT_IMAGE=qdrant/qdrant:v1.18.1
OLLAMA_IMAGE=ollama/ollama:0.24.0
WIKIJS_IMAGE=ghcr.io/requarks/wiki:2.5.314
WIKIJS_POSTGRES_IMAGE=postgres:16-alpine

# FastAPI Synapse webhook auth.
SYNAPSE_WEBHOOK_AUTH_TOKEN={token(48)}
SYNAPSE_AUTH_DISABLED=false

# Ollama models.
OLLAMA_INTERNAL_BASE_URL=http://ollama:11434
OLLAMA_HOST_BASE_URL=http://127.0.0.1:11434
# Recommended quality model: qwen2.5-coder:14b. Change these two model tags together.
OLLAMA_FORMAT_MODEL=tinyllama:latest
OLLAMA_ANSWER_MODEL=tinyllama:latest
OLLAMA_EMBED_MODEL=nomic-embed-text
OLLAMA_FORMAT_NUM_PREDICT=768
OLLAMA_ANSWER_NUM_PREDICT=256

# Wiki.js publisher. Replace WIKIJS_API_TOKEN after initial Wiki.js admin setup.
WIKIJS_DB_NAME=wiki
WIKIJS_DB_USER=wikijs
WIKIJS_DB_PASSWORD={token(24)}
WIKIJS_API_TOKEN=replace-after-wikijs-admin-setup
WIKIJS_LOCALE=en
WIKIJS_PUBLIC_BASE_URL=

# Qdrant/RAG.
QDRANT_COLLECTION_BASE=synapse_notes
QDRANT_COLLECTION=synapse_notes__nomic_embed_text__768
SYNAPSE_MANAGE_QDRANT_COLLECTION=true
RAG_TOP_K=5
RAG_CANDIDATE_K=25
RAG_SCORE_THRESHOLD=0.35
RAG_QUERY_TERM_MIN_COVERAGE=0.6
RAG_QUERY_TERM_MIN_MATCHES=2
RAG_DOMAIN_GLOSSARY_JSON={}

# Local lab resource limits.
SYNAPSE_MAX_CONTENT_BYTES=262144
SYNAPSE_MAX_CHUNKS_PER_NOTE=32
SYNAPSE_MAX_QUESTION_LENGTH=1000
SYNAPSE_MAX_PARALLEL_EXECUTIONS=2
SYNAPSE_EMBED_BATCH_SIZE=16
SYNAPSE_ANSWER_MODE=llm
SYNAPSE_ANSWER_VALIDATION=structural
RAG_QUOTE_OVERLAP_THRESHOLD=0.3

# Host-side helper scripts.
SYNAPSE_SERVICE_BASE_URL=http://localhost:15515
SYNAPSE_NOTE_WEBHOOK_URL=http://localhost:15515/webhook/synapse/note
SYNAPSE_ASK_WEBHOOK_URL=http://localhost:15515/webhook/synapse/ask
OBSIDIAN_VAULT_PATH=examples/obsidian-vault
"""
dst.write_text(text, encoding="utf-8")
print(dst)
PY

# ── Report what was generated vs what needs manual input ────────────────────
echo ""
echo "✅ .env created at $DST"
echo ""
echo "Generated automatically:"
echo "  • SYNAPSE_WEBHOOK_AUTH_TOKEN  — random 48-byte URL-safe token"
echo "  • WIKIJS_DB_PASSWORD           — random 24-byte URL-safe token"
echo ""
echo "⚠️  Still needs manual input:"
echo "  • WIKIJS_API_TOKEN             — set to 'replace-after-wikijs-admin-setup'"
echo "                                   Replace after completing Wiki.js admin setup (see below)."
echo "  • WIKIJS_PUBLIC_BASE_URL      — leave empty for container-internal URLs,"
echo "                                   or set to your browser-facing Wiki.js URL"
echo "                                   (e.g. http://localhost:3000) so API responses"
echo "                                   return clickable source links."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Wiki.js Manual Setup Steps"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  1.  Run:  scripts/e2e/start.sh"
echo "  2.  Open  http://localhost:3000  in your browser."
echo "  3.  Complete the Wiki.js initial admin setup wizard."
echo "  4.  Go to  Administration > Groups  and create a 'synapse' group with"
echo "      admin permissions."
echo "  5.  Go to  Administration > API Keys  and generate a new API key"
echo "      assigned to the 'synapse' group (scopes: read + write pages)."
echo "  6.  Copy the generated key and update .env:"
echo ""
echo "          WIKIJS_API_TOKEN=<your-api-key>"
echo ""
echo "  7.  Restart Synapse to pick up the new token:"
echo "          make lab-up"
echo "          # or: scripts/e2e/start-synapse.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Do not commit the .env file — it contains local secrets."